before_script:
  - pushd /opt/chapel/1.16.0/
  - make test-venv
  - popd

test:
  image: chapel/chapel-gasnet:1.16.0
  stage: test/unit
  script:
  - cd test/unit
  - start_test -junit-xml -numlocales 4