before_script:
  - pushd $CHPL_HOME
  - make test-venv
  - make chpldoc
  - popd

stages:
  - build
  - test
  - doc

test:
  image: chapel/chapel-gasnet:latest
  stage: test
  script:
  - cd test/unit
  - start_test -junit-xml -numlocales 4

chpldoc:
  image: chapel/chapel-gasnet:latest
  stage: doc
  script: chpldoc */*.chpl
  when: always