before_script:
  - pushd /opt/chapel/1.16.0/
  - make test-venv
  - popd

test:
  image: chapel/chapel
  stage: test
  services:
  - name: chapel/chapel-gasnet
    alias: chapel-1
  - name: chapel/chapel-gasnet
    alias: chapel-2
  - name: chapel/chapel-gasnet
    alias: chapel-3
  script:
  - cd test
  - start_test