before_script:
  - pushd $CHPL_HOME
  - make test-venv
  - make chpldoc
  - popd

stages:
  - build
  - test
  - doc

test:
  image: chapel/chapel:1.17.1
  stage: test
  script:
  - cd test/unit
  - start_test -junit-xml -numlocales 4

chpldoc:
  image: chapel/chapel:1.17.1
  stage: doc
  script: chpldoc src/*.chpl src/*/*.chpl
  when: always
  artifacts:
    paths: 
    - docs
    expire_in: 1 month
  allow_failure: true
