language: minimal

sudo: required

services:
  - docker

jobs:
  include:
    - script: |
        docker run -it -v ${TRAVIS_BUILD_DIR}:/repo.git -w /repo.git pnnl/chapel:master /bin/bash -c '
        cd test/unit
        start_test -junit-xml -numlocales 4'
#    - script: |
#        docker run -it -v ${TRAVIS_BUILD_DIR}:/repo.git -w /repo.git pnnl/chapel:master /bin/bash -c '
#        chpldoc src/*/*.chpl'

notifications:
    slack: hypergraphs:D6dV0BOxuu3GjVNcp3jokIXb
